StudentManagementSystem/Models/ViewModels/StudentBatchViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudentManagementSystem.Models.ViewModels
{
    public class StudentBatchViewModel
    {
        public string Id { get; set; }
        [Required(ErrorMessage ="student is required!")]
        public string StudentId { get; set; }
        [Required(ErrorMessage = "batch is required!")]
        public string BatchId { get; set; }
    }
}

StudentManagementSystem/Controllers/StudentBatchController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using StudentManagementSystem.DAO;
using StudentManagementSystem.Models.DataModels;
using StudentManagementSystem.Models.ViewModels;

namespace StudentManagementSystem.Controllers
{
    public class StudentBatchController : Controller
    {
        private readonly SMSDbContext _dbContext;
        public StudentBatchController(SMSDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        [Authorize]
        public IActionResult Index()
        {
            ViewBag.Id = Guid.NewGuid().ToString();

            ViewBag.Student = _dbContext.Students.Select(s => new StudentViewModel
            {
                Id = s.Id,
                Name = s.Name,
            }).OrderBy(o => o.Name).ToList();

            var batches = (from batch in _dbContext.Batches
                           join course in _dbContext.Courses
                           on batch.CourseId equals course.Id

                           select new BatchViewModel
                           {
                               Id = batch.Id,
                               Name = batch.Name + "/ " + course.Name
                           }).OrderBy(o => o.Name).ToList();
            ViewBag.Batch = batches;

            return View();
        }

        [Authorize]
        [HttpPost]
        public IActionResult Index(StudentBatchViewModel ui)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    StudentBatchEntity studentData = new StudentBatchEntity()
                    {
                        Id = ui.Id,
                        CreatedAt = DateTime.UtcNow,
                        IsInActive = true,
                        StudentId = ui.StudentId,
                        BatchId = ui.BatchId,
                    };
                    _dbContext.StudentBatches.Add(studentData);
                    _dbContext.SaveChanges();
                    TempData["info"] = "save successfully the data";
                }
                else
                {
                    ViewBag.Id = Guid.NewGuid().ToString();

                    ViewBag.Student = _dbContext.Students.Select(s => new StudentViewModel
                    {
                        Id = s.Id,
                        Name = s.Name,
                    }).OrderBy(o => o.Name).ToList();

                    var batches = (from batch in _dbContext.Batches
                                   join course in _dbContext.Courses
                                   on batch.CourseId equals course.Id

                                   select new BatchViewModel
                                   {
                                       Id = batch.Id,
                                       Name = batch.Name + "/ " + course.Name
                                   }).OrderBy(o => o.Name).ToList();
                    ViewBag.Batch = batches;

                    return View(ui);
                }
            }
            catch (Exception e)
            {
                TempData["info"] = "error while saving the data";
            }
            return RedirectToAction("List");
        }

        [Authorize]
        public IActionResult List()
        {
            IList<StudentBatchViewModel> studentList = (from sb in _dbContext.StudentBatches
                                                        join student in _dbContext.Students
                                                        on sb.StudentId equals student.Id
                                                        join batch in _dbContext.Batches
                                                        on sb.BatchId equals batch.Id
                                                        join course in _dbContext.Courses
                                                        on batch.CourseId equals course.Id

                                                        select new StudentBatchViewModel
                                                        {
                                                            Id = sb.Id,
                                                            StudentId = student.Name,
                                                            BatchId = batch.Name+"/ "+course.Name,
                                                        }).ToList();
            return View(studentList);
        }

        [Authorize]
        public IActionResult Detail()
        {
            IList<StudentBatchViewModel> studentDetail = (from sb in _dbContext.StudentBatches
                                                        join student in _dbContext.Students
                                                        on sb.StudentId equals student.Id
                                                        join batch in _dbContext.Batches
                                                        on sb.BatchId equals batch.Id
                                                        join course in _dbContext.Courses
                                                        on batch.CourseId equals course.Id

                                                        select new StudentBatchViewModel
                                                        {
                                                            Id = sb.BatchId,
                                                            StudentId = student.Name,
                                                            BatchId = batch.Name + "/ " + course.Name,
                                                        }).ToList();
            return View(studentDetail);
        }
        [Authorize]
        public IActionResult StudentDetail()
        {
            IList<StudentBatchViewModel> studentBatchDetail = (from sb in _dbContext.StudentBatches
                                                               join student in _dbContext.Students
                                                               on sb.StudentId equals student.Id
                                                               join batch in _dbContext.Batches
                                                               on sb.BatchId equals batch.Id
                                                               where sb.StudentId == student.Id && sb.BatchId == batch.Id

                                                               select new StudentBatchViewModel
                                                               {
                                                                   Id = sb.BatchId,
                                                                   StudentId = student.Name,
                                                                   BatchId = batch.Name,
                                                               }).ToList();
            return View(studentBatchDetail);
        }

        [Authorize]
        public IActionResult Delete(string Id)
        {
            try
            {
                var deleteStudentBatch = _dbContext.StudentBatches.Where(w => w.Id == Id).FirstOrDefault();
                if(deleteStudentBatch is not null)
                {
                    _dbContext.StudentBatches.Remove(deleteStudentBatch);
                    _dbContext.SaveChanges();
                }
                TempData["info"] = "delete successtully the data";
            }
            catch (Exception e)
            {
                TempData["info"] = "error while deleting the data";
            }
            return RedirectToAction("List");
        }

        [Authorize]
        public IActionResult Edit(string Id)
        {
            StudentBatchViewModel editStudentBatchData = _dbContext.StudentBatches.Where(w => w.Id == Id).Select(s => new StudentBatchViewModel
            {
                Id =s.Id,
                StudentId=s.StudentId,
                BatchId=s.BatchId,
            }).FirstOrDefault();

            ViewBag.Student = _dbContext.Students.Select(s => new StudentViewModel
            {
                Id = s.Id,
                Name = s.Name,
            }).OrderBy(o => o.Name).ToList();

            var batches = (from batch in _dbContext.Batches
                           join course in _dbContext.Courses
                           on batch.CourseId equals course.Id

                           select new BatchViewModel
                           {
                               Id = batch.Id,
                               Name = batch.Name + "/ " + course.Name
                           }).OrderBy(o => o.Name).ToList();
            ViewBag.Batch = batches;

            return View(editStudentBatchData);
        }

        [Authorize]
        public IActionResult Update(StudentBatchViewModel ui)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    StudentBatchEntity studentData = new StudentBatchEntity()
                    {
                        Id = ui.Id,
                        CreatedAt = DateTime.UtcNow,
                        ModifiedAt = DateTime.UtcNow,
                        IsInActive = true,
                        StudentId = ui.StudentId,
                        BatchId = ui.BatchId,
                    };
                    _dbContext.StudentBatches.Update(studentData);
                    _dbContext.SaveChanges();
                    TempData["info"] = "update successfully the data";
                }
                else
                {
                    ViewBag.Id = Guid.NewGuid().ToString();

                    ViewBag.Student = _dbContext.Students.Select(s => new StudentViewModel
                    {
                        Id = s.Id,
                        Name = s.Name,
                    }).OrderBy(o => o.Name).ToList();

                    var batches = (from batch in _dbContext.Batches

StudentManagementSystem/Views/StudentBatch/Detail.cshtml
@model IList<StudentBatchViewModel>
<div class="container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/home/index">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Student</li>
        </ol>
    </nav>
    @if (User.IsInRole("Admin") || User.Identity.IsAuthenticated)
    {
        <h1 class="h4 mt-3">Students: </h1>
        <div class="row my-3">
            @foreach (var detail in Model)
            {
                if (detail == null)
                {
                    <p class="alert alert-info" role="alert">No Chapter In Here!</p>
                }
                <div class="col-lg-4">
                    <div class="card">
                        <div class="card-body">
                            <h1 class="h5"><span class="fw-bold">Student: </span> @detail.StudentId</h1>
                            <p class="card-text"><span class="fw-bold">Batch: </span> @detail.BatchId</p>

                        </div>
                        <div class="card-footer">
                            <a asp-controller="Batch" asp-action="StudentDetail" asp-route-Id="@detail.Id" class="btn btn-primary float-end">Details >></a>
                        </div>
                    </div>
                </div>
            }

        </div>
    }
</div>

StudentManagementSystem/Views/StudentBatch/Edit.cshtml
@model StudentManagementSystem.Models.ViewModels.StudentBatchViewModel
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/home/index">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Edit</li>
    </ol>
</nav>
<div class="container w-50 mx-auto mt-5 p-5 border-start border-end border-bottom rounded-start rounded-end shadow-sm" style="border-top: 12px solid #699BF7;">
    <div class="d-flex justify-content-center align-items-center mb-4">
        <div class="me-3">
            <i class="fa-solid fa-book-open fa-2xl" style="color: #699BF7"></i>
        </div>
        <div class="text-center">
            <span class="mate-sc text-uppercase fw-bold">Leadership</span>
            <h1 class="h5 brand-space">Excellence</h1>
        </div>
    </div>
    <h1 class="h4 mb-3 text-center">Student Batch Entry Form</h1>
    <form asp-controller="StudentBatch" asp-action="Update" enctype="multipart/form-data">
        <input asp-for="Id" value="@Model.Id" type="hidden" />
        <div class="mb-3">
            <label asp-for="StudentId" class="form-label">Student</label>
            <select asp-for="StudentId" class="form-select">
                <option value="">---choose student---</option>
                @foreach (var student in ViewBag.Student)
                {
                    if(@student.Id == Model.StudentId)
                    {
                        <option value="@student.Id" selected>@student.Name</option>
                    }
                }
            </select>
            <span asp-validation-for="StudentId" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="BatchId" class="form-label">Batch</label>
            <select asp-for="BatchId" class="form-select">
                <option value="">---choose student---</option>
                @foreach (var batch in ViewBag.Batch)
                {
                    if(@batch.Id == Model.BatchId)
                    {
                        <option value="@batch.Id" selected>@batch.Name</option>
                    }
                }
            </select>
            <span asp-validation-for="BatchId" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <button class="btn btn-primary" role="button" type="submit">Update</button>
            <a href="/studentbatch/cancle" class="btn btn-danger" style="border-radius: 10px 0 10px 0;">
                Cancel
            </a>
        </div>
    </form>
</div>

StudentManagementSystem/Views/StudentBatch/Index.cshtml
@model StudentManagementSystem.Models.ViewModels.StudentBatchViewModel
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/home/index">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Entry</li>
    </ol>
</nav>
<div class="container w-50 mx-auto mt-5 p-5 border-start border-end border-bottom rounded-start rounded-end shadow-sm" style="border-top: 12px solid #699BF7;">
    <div class="d-flex justify-content-center align-items-center mb-4">
        <div class="me-3">
            <i class="fa-solid fa-book-open fa-2xl" style="color: #699BF7"></i>
        </div>
        <div class="text-center">
            <span class="mate-sc text-uppercase fw-bold">Leadership</span>
            <h1 class="h5 brand-space">Excellence</h1>
        </div>
    </div>
    <h1 class="h4 mb-3 text-center">Student Batch Entry Form</h1>
    <form asp-controller="StudentBatch" asp-action="Index" enctype="multipart/form-data">
        <input asp-for="Id" value="@ViewBag.Id" type="hidden" />
        <div class="mb-3">
            <label asp-for="StudentId" class="form-label">Student</label>
            <select asp-for="StudentId" class="form-select">
                <option value="" selected>---choose student---</option>
                @foreach (var student in ViewBag.Student)
                {
                    <option value="@student.Id">@student.Name</option>
                }
            </select>
            <span asp-validation-for="StudentId" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="BatchId" class="form-label">Batch</label>
            <select asp-for="BatchId" class="form-select">
                <option value="" selected>---choose student---</option>
                @foreach (var batch in ViewBag.Batch)
                {
                    <option value="@batch.Id">@batch.Name</option>
                }
            </select>
            <span asp-validation-for="BatchId" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <button class="btn btn-primary" role="button" type="submit">Submit</button>
            <a href="/studentbatch/cancle" class="btn btn-danger" style="border-radius: 10px 0 10px 0;">
                Cancel
            </a>
        </div>
    </form>
</div>

StudentManagementSystem/Views/StudentBatch/List.cshtml
@model IList<StudentBatchViewModel>
@if (TempData["info"] != null)
{
    @if (TempData["info"].ToString().Contains("delete"))
    {
        <div class="alert alert-danger mt-3" role="alert">
            @TempData["info"]
        </div>
    }
    else
    {
        <div class="alert alert-success mt-3" role="alert">
            @TempData["info"]
        </div>
    }
}


<div class="container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/home/index">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">List</li>
        </ol>
    </nav>
    @if (User.IsInRole("Admin"))
    {

        <div class="row">
            <h1 class="h4 my-3">Student Batch List</h1>

            <div class="col-md-12">
                <div class="table-responsive">
                    <table id="studentBatchTable" class="table table-bordred table-striped">

                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Student</th>
                                <th>Batch</th>
                        
                                    @if (User.IsInRole("Admin"))
                                    {

                                    <th>Action</th>
                                    }
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                int index = 1;
                            }
                            
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@index</td>
                                    <td>@item.StudentId</td>
                                    <td>@item.BatchId</td>
                                    
                                    @if (User.IsInRole("Admin"))
                                    {
                                        <td>
                                            <div class="dropdown">
                                                <button class="btn btn-white dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">Action</button>
                                                    <ul class="dropdown-menu">

                                                        <li>
                                                            <a type="button" class="dropdown-item btn text-info btn-xs mb-2" href="/studentbatch/edit?Id=@item.Id">
                                                                <i class="fa-regular fa-pen-to-square"></i> Edit
                                                            </a>
                                                        </li>
                                                        <li class="">
                                                            <a type="button" class="dropdown-item btn text-danger btn-xs " asp-controller="StudentBatch" asp-action="Delete" asp-route-Id="@item.Id" onclick="return confirm('Are you sure want to delete the record?')">
                                                                <i class="fa-regular fa-trash-can"></i> Delete
                                                            </a>
                                                        </li>
                                                    </ul>
                                            </div>
                                        </td>
                                    }
                                </tr>
                                index++;
                            }


                        </tbody>

                    </table>
                </div>
            </div>
        </div>
    }
</div>

<script>
    $(document).ready(function () {
        $('#studentBatchTable').DataTable();
    });
</script>

StudentManagementSystem/Views/StudentBatch/StudentDetail.cshtml
@model IList<StudentBatchViewModel>
<div class="container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/home/index">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Student</li>
        </ol>
    </nav>
    @if (User.IsInRole("Admin") || User.Identity.IsAuthenticated)
    {
        <h1 class="h4 mt-3">Batch: </h1>
        <div class="row my-3">
            @foreach (var detail in Model)
            {
                if (detail == null)
                {
                    <p class="alert alert-info" role="alert">No Chapter In Here!</p>
                }
                <div class="col-lg-4">
                    <div class="card">
                        <div class="card-body">
                            <h1 class="h5"><span class="fw-bold">Student: </span> @detail.StudentId</h1>
                            <p class="card-text"><span class="fw-bold">Batch: </span> @detail.BatchId</p>
                            
                        </div>
                        <div class="card-footer">
                            <a asp-controller="Batch" asp-action="StudentDetail" asp-route-Id="@detail.Id" class="btn btn-primary float-end">Details >></a>
                        </div>
                    </div>
                </div>
            }

        </div>
    }
</div>