StudentManagementSystem/Models/ViewModels/StudentViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudentManagementSystem.Models.ViewModels
{
    public class StudentViewModel
    {
        public string Id { get; set; }
        [Required(ErrorMessage ="Name is requied")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Email is requied")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [Required(ErrorMessage = "Phone is requied")]
        public string Phone { get; set; }
        [Required(ErrorMessage = "Address is requied")]
        public string Address { get; set; }
        [Required(ErrorMessage = "NRC is requied")]
        public string NRC { get; set; }
        [Required(ErrorMessage = "Date of birth is requied")]
        [DataType(DataType.Date)]
        public DateTime DOB { get; set; }
        [Required(ErrorMessage = "Father name is requied")]
        public string FatherName { get; set; }
        [Required(ErrorMessage = "Gender is requied")]
        public string Gender { get; set; }
        public string AspNetUsersId { get; set; }
        

    }
}

StudentManagementSystem/Controllers/BatchController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StudentManagementSystem.DAO;
using StudentManagementSystem.Models.DataModels;
using StudentManagementSystem.Models.ViewModels;
using System.Security.Claims;

namespace StudentManagementSystem.Controllers
{
    public class BatchController : Controller
    {
        private readonly SMSDbContext _dbContext;
        public BatchController(SMSDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [Authorize]
        public IActionResult Entry()
        {
            var id = Guid.NewGuid().ToString();
            ViewBag.Id = id;

            var courses = _dbContext.Courses.Select(s => new CourseViewModel
            {
                Id = s.Id,
                Name = s.Name,
            }).OrderBy(o => o.Name).ToList();
            ViewBag.Course = courses;

            return View();
        }

        [Authorize]
        [HttpPost]
        public IActionResult Entry(BatchViewModel ui)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    BatchEntity batchData = new BatchEntity()
                    {
                        Id = ui.Id,
                        CreatedAt = DateTime.UtcNow,
                        IsInActive = true,
                        Name = ui.Name,
                        Description = ui.Description,
                        CourseId = ui.CourseId,
                        OpeningDate = ui.OpeningDate,
                        DurationInHour = ui.DurationInHour,
                        DurationInMonth = ui.DurationInMonth,
                    };
                    _dbContext.Batches.Add(batchData);
                    _dbContext.SaveChanges();
                    TempData["info"] = "save successfully the record";
                }
                else
                {
                    // Reload course and id to populate the dropdown again
                    var id = Guid.NewGuid().ToString();
                    ViewBag.Id = id;
                    var courses = _dbContext.Courses.Select(s => new CourseViewModel
                    {
                        Id = s.Id,
                        Name = s.Name,
                    }).OrderBy(o => o.Name).ToList();
                    ViewBag.Course = courses;

                    return View(ui);
                }

            }
            catch (Exception e)
            {
                TempData["info"] = "error while saving the record";
            }

            return RedirectToAction("List");
        }

        [Authorize]
        public IActionResult List()
        {
            IList<BatchViewModel> batchList = (from batch in _dbContext.Batches
                                               join course in _dbContext.Courses
                                               on batch.CourseId equals course.Id

                                               select new BatchViewModel
                                               {
                                                   Id = batch.Id,
                                                   Name = batch.Name,
                                                   Description = batch.Description,
                                                   CourseId = course.Name,
                                                   OpeningDate = batch.OpeningDate,
                                                   DurationInHour = batch.DurationInHour,
                                                   DurationInMonth = batch.DurationInMonth,
                                               }).ToList();

            
            return View(batchList);
        }
        
        [Authorize]
        public IActionResult Detail()
        {
            IList<BatchViewModel> batchDetail = (from batch in _dbContext.Batches
                                                 join course in _dbContext.Courses
                                                 on batch.CourseId equals course.Id
                                                 
                                                 where batch.CourseId == course.Id 

                                                 select new BatchViewModel
                                                 {
                                                     Id = batch.Id,
                                                     Name = batch.Name,
                                                     Description = batch.Description,
                                                     CourseId = course.Name,
                                                     OpeningDate = batch.OpeningDate,
                                                     DurationInHour = batch.DurationInHour,
                                                     DurationInMonth = batch.DurationInMonth,
                                                 }).ToList();
            return View(batchDetail);
        }

        [Authorize]
        public IActionResult AdminDetail(string Id)
        {
            IList<BatchViewModel> batchDetail = (from batch in _dbContext.Batches
                                                 join course in _dbContext.Courses
                                                 on batch.CourseId equals course.Id

                                                 where batch.CourseId == Id

                                                 select new BatchViewModel
                                                 {
                                                     Id = batch.Id,
                                                     Name = batch.Name,
                                                     Description = batch.Description,
                                                     CourseId = course.Name,
                                                     OpeningDate = batch.OpeningDate,
                                                     DurationInHour = batch.DurationInHour,
                                                     DurationInMonth = batch.DurationInMonth,
                                                 }).ToList();
            return View(batchDetail);
        }

        [Authorize]
        public IActionResult TeacherDetail(string Id)
        {
            IList<BatchViewModel> teacherBatchDetail = (from batch in _dbContext.Batches
                                                 join course in _dbContext.Courses
                                                 on batch.CourseId equals course.Id
                                                 join tc in _dbContext.TeacherCourses
                                                 on course.Id equals tc.CourseId
                                                 join teacher in _dbContext.Teachers
                                                 on tc.TeacherId equals teacher.Id

                                                 where teacher.Email == Id || tc.CourseId==Id

                                                 select new BatchViewModel
                                                 {
                                                     Id = batch.Id,
                                                     Name = batch.Name,
                                                     Description = batch.Description,
                                                     CourseId = course.Name,
                                                     OpeningDate = batch.OpeningDate,
                                                     DurationInHour = batch.DurationInHour,
                                                     DurationInMonth = batch.DurationInMonth,
                                                 }).ToList();
            return View(teacherBatchDetail);
        }

        [Authorize]
        public IActionResult StudentDetail(string Id)
        {

            IList<BatchViewModel> studentBatchDetail = (from batch in _dbContext.Batches
                                                   join sb in _dbContext.StudentBatches
                                                   on batch.Id equals sb.BatchId
                                                    join student in _dbContext.Students
                                                    on sb.StudentId equals student.Id
                                                    join course in _dbContext.Courses
                                                    on batch.CourseId equals course.Id

                                                    where student.Email == Id || sb.BatchId == Id || batch.CourseId==Id

                                                   select new BatchViewModel
                                            {
                                                Id = sb.BatchId,
                                                Name = batch.Name,
                                                Description = batch.Description,
                                                CourseId = course.Name+"/ "+batch.Name,
                                                OpeningDate = batch.OpeningDate,
                                                DurationInHour = batch.DurationInHour,
                                                DurationInMonth = batch.DurationInMonth,
                                            }).ToList();
            return View(studentBatchDetail);
        }
        [Authorize]
        public IActionResult Delete(string Id)
        {
            try
            {
                var deleteBatchData = _dbContext.Batches.Where(w => w.Id == Id).FirstOrDefault();

                if(deleteBatchData is not null)
                {
                    _dbContext.Batches.Remove(deleteBatchData);
                    _dbContext.SaveChanges();
                }
                TempData["info"] = "delete successfully the record";
            }
            catch (Exception e)
            {

StudentManagementSystem/Controllers/StudentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StudentManagementSystem.DAO;
using StudentManagementSystem.Models.DataModels;
using StudentManagementSystem.Models.ViewModels;
using System.Security.Claims;

namespace StudentManagementSystem.Controllers
{
    public class StudentController : Controller
    {
        private readonly SMSDbContext _dbContext;
        public StudentController(SMSDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [Authorize]
        public IActionResult Entry()
        {
            ViewBag.Id = Guid.NewGuid().ToString();

            ViewBag.AspUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);


            var courses = _dbContext.Courses.Select(s => new CourseViewModel
            {
                Id = s.Id,
                Name = s.Name,
            }).OrderBy(o => o.Name).ToList();
            ViewBag.Course = courses;

            return View();
        }

        [HttpPost]
        [Authorize]
        public IActionResult Entry(StudentViewModel ui)
        {
            

            try
            {
                if (ModelState.IsValid)
                {

                    StudentEntity studentData = new StudentEntity()
                    {
                        Id = ui.Id,
                        CreatedAt = DateTime.UtcNow,
                        IsInActive = true,
                        Name = ui.Name,
                        Email = ui.Email,
                        Phone = ui.Phone,
                        Address = ui.Address,
                        NRC = ui.NRC,
                        DOB = ui.DOB,
                        FatherName = ui.FatherName,
                        Gender = ui.Gender,
                        AspNetUsersId = ui.AspNetUsersId,
                    };
                    _dbContext.Students.Add(studentData);
                    _dbContext.SaveChanges();
                    TempData["info"] = "save successfully data";
                }
                else
                {
                    //Relodad Id,AspUserId and BatchId to populat the dropdown again

                    ViewBag.Id = Guid.NewGuid().ToString();

                    ViewBag.AspUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);


                    return View(ui);
                }
            }
            catch(Exception e)
            {
                TempData["info"] = "error while saving data";
            }
            return RedirectToAction("list");
        }

        
        [Authorize]
        public IActionResult List()
        {
            IList<StudentViewModel> studentList = _dbContext.Students.Select(s => new StudentViewModel
            {
                Id = s.Id,
                Name = s.Name,
                Email = s.Email,
                Phone = s.Phone,
                Address = s.Address,
                NRC = s.NRC,
                DOB = s.DOB,
                FatherName = s.FatherName,
                Gender = s.Gender,
            }).ToList();

            return  View(studentList);
        }

        
        [Authorize]
        public IActionResult Delete(string Id)
        {
            try
            {
                var deleteStudentData = _dbContext.Students.FirstOrDefault(w => w.Id == Id);
                if(deleteStudentData is not null)
                {
                    _dbContext.Students.Remove(deleteStudentData);
                    _dbContext.SaveChanges();
                }
                TempData["info"] = "delete successfully data";
            }
            catch(Exception e)
            {
                TempData["info"] = "error while deleting data";
            }
            return RedirectToAction("list");
        }

        [Authorize]
        public IActionResult Edit(string Id)
        {
            StudentViewModel editStudentData = _dbContext.Students.Where(w => w.Id == Id).Select(s => new StudentViewModel
            {
                Id = s.Id,
                AspNetUsersId = s.AspNetUsersId,
                Name = s.Name,
                Email = s.Email,
                Phone = s.Phone,
                Address = s.Address,
                NRC = s.NRC,
                DOB = s.DOB,
                FatherName = s.FatherName,
                Gender = s.Gender,

            }).FirstOrDefault();


            return View(editStudentData);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Update(StudentViewModel ui)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    StudentEntity updateStudentData = new StudentEntity()
                    {
                        Id = ui.Id,
                        CreatedAt = DateTime.UtcNow,
                        ModifiedAt = DateTime.UtcNow,
                        IsInActive = true,
                        Name = ui.Name,
                        Email = ui.Email,
                        Phone = ui.Phone,
                        Address = ui.Address,
                        NRC = ui.NRC,
                        DOB = ui.DOB,
                        FatherName = ui.FatherName,
                        Gender = ui.Gender,
                        AspNetUsersId = ui.AspNetUsersId,

                    };

                    _dbContext.Students.Update(updateStudentData);
                    _dbContext.SaveChanges();
                    TempData["info"] = "update successfully";
                }
                else
                {

                    return View("Edit", model: ui);
                }
            }
            catch(Exception e)
            {
                TempData["info"] = "error while updating data";
            }
            if (User.IsInRole("Admin"))
            {
                return RedirectToAction("List");
            }
            else
            {
                
                return Redirect("/Home/Index");
            }
        }

        [Authorize]
        public IActionResult Cancle(StudentViewModel ui)
        {
            StudentEntity student = new StudentEntity()
            {
                Name = "",
                Email = "",
                Phone = "",
                Address = "",
                NRC = "",
                DOB = DateTime.Now,
                FatherName = "",
                Gender = "",
            };
                return RedirectToAction("entry");
            
        }
    }
}

StudentManagementSystem/Views/Student/Detail.cshtml
@model StudentViewModel
<div class="container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/home/index">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Student</li>
        </ol>
    </nav>
    <div class="row">

        <h1 class="h4 mb-3">Student List</h1>
        <div class="col-md-12">
            <div class="table-responsive">
                <table id="adminTable" class="table table-bordred table-striped">

                    <thead>
                        <th scope="col">ID</th>
                        <th scope="col">Name</th>
                        <th>Email</th>
                        <th>Address</th>
                        <th>Phone</th>
                        <th>DOB</th>
                        <th>NRC</th>
                        <th>Gender</th>
                        <th>Father Name</th>

                    </thead>
                    <tbody>
                        @{
                            int index = 1;
                        }


                        <tr>
                            <td>@index</td>
                            <td>@Model.Name</td>
                            <td>@Model.Email</td>
                            <td>@Model.Address</td>
                            <td>@Model.Phone</td>
                            <td>@Model.DOB.ToString("dd-MM-yyyy")</td>
                            <td>@Model.NRC</td>
                            <td>@Model.Gender</td>
                            <td>@Model.FatherName</td>
                            <td>
                                <a asp-controller="Batch" asp-action="StudentDetail" asp-route-id="@Model.Id" class="link-underline-primary link-underline-opacity-100-hover">Details>></a>
                            </td>
                            </td>
                        </tr>


                    </tbody>

                </table>
            </div>
        </div>
    </div>
</div>

StudentManagementSystem/Views/Student/Edit.cshtml
@model StudentManagementSystem.Models.ViewModels.StudentViewModel
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/home/index">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Edit</li>
    </ol>
</nav>
<div class="container w-50 mx-auto mt-5 p-5 border-start border-end border-bottom rounded-start rounded-end shadow-sm" style="border-top: 12px solid #699BF7">
    <div class="d-flex justify-content-center align-items-center mb-4">
        <div class="me-3">
            <i class="fa-solid fa-book-open fa-2xl" style="color: #699BF7"></i>
        </div>
        <div class="text-center">
            <span class="mate-sc text-uppercase fw-bold">Leadership</span>
            <h1 class="h5 brand-space">Excellence</h1>
        </div>
    </div>
    <h1 class="h4 mb-3 text-center">To Edit Student </h1>
    <form asp-controller="Student" asp-action="Update" method="post" enctype="multipart/form-data">
        <input asp-for="Id" hidden />
        <input asp-for="AspNetUsersId" hidden />
        <div class="mb-3">
            <label asp-for="Name" class="form-label">Name</label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="Email" class="form-label">Email</label>
            <input asp-for="Email" class="form-control"/>
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Address" class="form-label">Address</label>
            <textarea asp-for="Address" class="form-control" rows="6" cols="6"></textarea>
            <span asp-validation-for="Address" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Phone" class="form-label">Phone</label>
            <input asp-for="Phone" class="form-control" />
            <span asp-validation-for="Phone" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="DOB" class="form-label">DOB</label>
            <input asp-for="DOB" class="form-control" />
            <span asp-validation-for="DOB" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="FatherName" class="form-label">Father Name</label>
            <input asp-for="FatherName" class="form-control" />
            <span asp-validation-for="FatherName" class="text-danger"></span>
        </div>
        <label class="form-label">Gender</label>
        <div class="mb-3">
            <div class="d-flex">

                <div class="me-3">
                    <input type="radio" name="Gender" id="male" value="Male" class="form-check-input" @(Model.Gender=="Male"?"Checked":"")/>
                    <label for="male" class="form-check-label">Male</label>
                </div>
                <div class="me-3">
                    <input type="radio" name="Gender" id="female" value="Female" class="form-check-input" @(Model.Gender == "Female" ? "Checked" : "") />
                    <label for="female" class="form-check-label">Female</label>
                </div>
                <div class="me-3">
                    <input type="radio" name="Gender" id="female" value="Other" class="form-check-input" @(Model.Gender == "Other" ? "Checked" : "") />
                    <label for="other" class="form-check-label">Other</label>
                </div>
            </div>
            <span asp-validation-for="Gender" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="NRC" class="form-label">NRC</label>
            <input asp-for="NRC" class="form-control" />
            <span asp-validation-for="NRC" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <button class="btn btn-primary text-white" style="border-radius: 10px 0 10px 0;">Update</button>
            <a href="/student/cancle" class="btn btn-danger" style="border-radius: 10px 0 10px 0;">
                Cancel
            </a>
        </div>
    </form>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

StudentManagementSystem/Views/Student/Entry.cshtml
@model StudentManagementSystem.Models.ViewModels.StudentViewModel
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/home/index">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Entry</li>
    </ol>
</nav>
<div class="container w-50 mx-auto mt-5 p-5 border-start border-end border-bottom rounded-start rounded-end shadow-sm" style="border-top: 12px solid #699BF7">
    <div class="d-flex justify-content-center align-items-center mb-4">
        <div class="me-3">
            <i class="fa-solid fa-book-open fa-2xl" style="color: #699BF7"></i>
        </div>
        <div class="text-center">
            <span class="mate-sc text-uppercase fw-bold">Leadership</span>
            <h1 class="h5 brand-space">Excellence</h1>
        </div>
    </div>
    <h1 class="h4 mb-3 text-center">Student Entry Form</h1>
    <form asp-controller="Student" asp-action="Entry" method="post" enctype="multipart/form-data">
        <input asp-for="Id" value="@ViewBag.Id" hidden />
        <input asp-for="AspNetUsersId" value="@ViewBag.AspUserId" hidden />
        <div class="mb-3">
            <label asp-for="Name" class="form-label">Name</label>
            <input asp-for="Name" class="form-control" placeholder="Enter Name..." />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="Email" class="form-label">Email</label>
            <input asp-for="Email" class="form-control" placeholder="Enter Email..." />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Address" class="form-label">Address</label>
            <textarea asp-for="Address" class="form-control" rows="6" cols="6"></textarea>
            <span asp-validation-for="Address" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Phone" class="form-label">Phone</label>
            <input asp-for="Phone" class="form-control" placeholder="Enter Phone..." />
            <span asp-validation-for="Phone" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="DOB" class="form-label">Date Of Birth</label>
            <input asp-for="DOB" class="form-control" placeholder="Enter Date Of Birth..." />
            <span asp-validation-for="DOB" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="FatherName" class="form-label">Father Name</label>
            <input asp-for="FatherName" class="form-control" placeholder="Enter Father's Name..." />
            <span asp-validation-for="FatherName" class="text-danger"></span>
        </div>
        <label class="form-label">Gender</label>
        <div class="mb-3">
            <div class="d-flex">

                <div class="me-3">
                    <input type="radio" asp-for="Gender" id="male" value="Male" class="form-check-input"/>
                    <label for="male" class="form-check-label">Male</label>
                </div>
                <div class="me-3">
                    <input type="radio" asp-for="Gender" id="female" value="Female" class="form-check-input" />
                    <label for="female" class="form-check-label">Female</label>
                </div>
                <div class="me-3">
                    <input type="radio" asp-for="Gender" id="female" value="Other" class="form-check-input" />
                    <label for="other" class="form-check-label">Female</label>
                </div>
            </div>
            <span asp-validation-for="Gender" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="NRC" class="form-label">NRC</label>
            <input asp-for="NRC" class="form-control" placeholder="Enter NRC..." />
            <span asp-validation-for="NRC" class="text-danger"></span>
        </div>
        
        <div class="mb-3">
            <button class="btn btn-primary text-white" style="border-radius: 10px 0 10px 0;">Submit</button>
            <a href="/student/cancle" class="btn btn-danger" style="border-radius: 10px 0 10px 0;">
                Cancel
            </a>
        </div>
    </form>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}