StudentManagementSystem/Models/ViewModels/CourseViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace StudentManagementSystem.Models.ViewModels
{
    public class CourseViewModel
    {
        public string Id { get; set; }
        [Required(ErrorMessage ="Name is required")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Description is required")]
        public string Description { get; set; }

    }
}

StudentManagementSystem/Controllers/BatchController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StudentManagementSystem.DAO;
using StudentManagementSystem.Models.DataModels;
using StudentManagementSystem.Models.ViewModels;
using System.Security.Claims;

namespace StudentManagementSystem.Controllers
{
    public class BatchController : Controller
    {
        private readonly SMSDbContext _dbContext;
        public BatchController(SMSDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [Authorize]
        public IActionResult Entry()
        {
            var id = Guid.NewGuid().ToString();
            ViewBag.Id = id;

            var courses = _dbContext.Courses.Select(s => new CourseViewModel
            {
                Id = s.Id,
                Name = s.Name,
            }).OrderBy(o => o.Name).ToList();
            ViewBag.Course = courses;

            return View();
        }

        [Authorize]
        [HttpPost]
        public IActionResult Entry(BatchViewModel ui)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    BatchEntity batchData = new BatchEntity()
                    {
                        Id = ui.Id,
                        CreatedAt = DateTime.UtcNow,
                        IsInActive = true,
                        Name = ui.Name,
                        Description = ui.Description,
                        CourseId = ui.CourseId,
                        OpeningDate = ui.OpeningDate,
                        DurationInHour = ui.DurationInHour,
                        DurationInMonth = ui.DurationInMonth,
                    };
                    _dbContext.Batches.Add(batchData);
                    _dbContext.SaveChanges();
                    TempData["info"] = "save successfully the record";
                }
                else
                {
                    // Reload course and id to populate the dropdown again
                    var id = Guid.NewGuid().ToString();
                    ViewBag.Id = id;
                    var courses = _dbContext.Courses.Select(s => new CourseViewModel
                    {
                        Id = s.Id,
                        Name = s.Name,
                    }).OrderBy(o => o.Name).ToList();
                    ViewBag.Course = courses;

                    return View(ui);
                }

            }
            catch (Exception e)
            {
                TempData["info"] = "error while saving the record";
            }

            return RedirectToAction("List");
        }

        [Authorize]
        public IActionResult List()
        {
            IList<BatchViewModel> batchList = (from batch in _dbContext.Batches
                                               join course in _dbContext.Courses
                                               on batch.CourseId equals course.Id

                                               select new BatchViewModel
                                               {
                                                   Id = batch.Id,
                                                   Name = batch.Name,
                                                   Description = batch.Description,
                                                   CourseId = course.Name,
                                                   OpeningDate = batch.OpeningDate,
                                                   DurationInHour = batch.DurationInHour,
                                                   DurationInMonth = batch.DurationInMonth,
                                               }).ToList();

            
            return View(batchList);
        }
        
        [Authorize]
        public IActionResult Detail()
        {
            IList<BatchViewModel> batchDetail = (from batch in _dbContext.Batches
                                                 join course in _dbContext.Courses
                                                 on batch.CourseId equals course.Id
                                                 
                                                 where batch.CourseId == course.Id 

                                                 select new BatchViewModel
                                                 {
                                                     Id = batch.Id,
                                                     Name = batch.Name,
                                                     Description = batch.Description,
                                                     CourseId = course.Name,
                                                     OpeningDate = batch.OpeningDate,
                                                     DurationInHour = batch.DurationInHour,
                                                     DurationInMonth = batch.DurationInMonth,
                                                 }).ToList();
            return View(batchDetail);
        }

        [Authorize]
        public IActionResult AdminDetail(string Id)
        {
            IList<BatchViewModel> batchDetail = (from batch in _dbContext.Batches
                                                 join course in _dbContext.Courses
                                                 on batch.CourseId equals course.Id

                                                 where batch.CourseId == Id

                                                 select new BatchViewModel
                                                 {
                                                     Id = batch.Id,
                                                     Name = batch.Name,
                                                     Description = batch.Description,
                                                     CourseId = course.Name,
                                                     OpeningDate = batch.OpeningDate,
                                                     DurationInHour = batch.DurationInHour,
                                                     DurationInMonth = batch.DurationInMonth,
                                                 }).ToList();
            return View(batchDetail);
        }

        [Authorize]
        public IActionResult TeacherDetail(string Id)
        {
            IList<BatchViewModel> teacherBatchDetail = (from batch in _dbContext.Batches
                                                 join course in _dbContext.Courses
                                                 on batch.CourseId equals course.Id
                                                 join tc in _dbContext.TeacherCourses
                                                 on course.Id equals tc.CourseId
                                                 join teacher in _dbContext.Teachers
                                                 on tc.TeacherId equals teacher.Id

                                                 where teacher.Email == Id || tc.CourseId==Id

                                                 select new BatchViewModel
                                                 {
                                                     Id = batch.Id,
                                                     Name = batch.Name,
                                                     Description = batch.Description,
                                                     CourseId = course.Name,
                                                     OpeningDate = batch.OpeningDate,
                                                     DurationInHour = batch.DurationInHour,
                                                     DurationInMonth = batch.DurationInMonth,
                                                 }).ToList();
            return View(teacherBatchDetail);
        }

        [Authorize]
        public IActionResult StudentDetail(string Id)
        {

            IList<BatchViewModel> studentBatchDetail = (from batch in _dbContext.Batches
                                                   join sb in _dbContext.StudentBatches
                                                   on batch.Id equals sb.BatchId
                                                    join student in _dbContext.Students
                                                    on sb.StudentId equals student.Id
                                                    join course in _dbContext.Courses
                                                    on batch.CourseId equals course.Id

                                                    where student.Email == Id || sb.BatchId == Id || batch.CourseId==Id

                                                   select new BatchViewModel
                                            {
                                                Id = sb.BatchId,
                                                Name = batch.Name,
                                                Description = batch.Description,
                                                CourseId = course.Name+"/ "+batch.Name,
                                                OpeningDate = batch.OpeningDate,
                                                DurationInHour = batch.DurationInHour,
                                                DurationInMonth = batch.DurationInMonth,
                                            }).ToList();
            return View(studentBatchDetail);
        }
        [Authorize]
        public IActionResult Delete(string Id)
        {
            try
            {
                var deleteBatchData = _dbContext.Batches.Where(w => w.Id == Id).FirstOrDefault();

                if(deleteBatchData is not null)
                {
                    _dbContext.Batches.Remove(deleteBatchData);
                    _dbContext.SaveChanges();
                }
                TempData["info"] = "delete successfully the record";
            }
            catch (Exception e)
            {

StudentManagementSystem/Controllers/CourseController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StudentManagementSystem.DAO;
using StudentManagementSystem.Models.DataModels;
using StudentManagementSystem.Models.ViewModels;

namespace StudentManagementSystem.Controllers
{
    public class CourseController : Controller
    {
        private readonly SMSDbContext _dbContext;
        public CourseController(SMSDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [Authorize]
        public IActionResult Entry()
        {
            var id = Guid.NewGuid().ToString();
            ViewBag.Id = id;

            return View();
        }

        [HttpPost]
        [Authorize]
        public IActionResult Entry(CourseViewModel ui)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    CourseEntity courseData = new CourseEntity()
                    {
                        Id = ui.Id,
                        CreatedAt = DateTime.UtcNow,
                        IsInActive = true,
                        Name = ui.Name,
                        Description = ui.Description,
                        
                    };
                    _dbContext.Courses.Add(courseData);
                    _dbContext.SaveChanges();
                    TempData["info"] = "save successfully the record";
                }
                else
                {
                    //Reload id to populate the dropdown again
                    var id = Guid.NewGuid().ToString();
                    ViewBag.Id = id;

                    return View(ui);
                }
            }
            catch (Exception e)
            {
                TempData["info"] = "error while saving the record";
            }
            return RedirectToAction("List");
        }

        [Authorize]
        public IActionResult List()
        {
            IList<CourseViewModel> courseList = _dbContext.Courses.Select(s => new CourseViewModel
            {
                Id = s.Id,
                Name = s.Name,
                Description = s.Description,
                
            }).ToList();

            return View(courseList);
        }

        [Authorize]
        public IActionResult Detail()
        {
            IList<CourseViewModel> courseDetail = _dbContext.Courses.Select(s => new CourseViewModel
            {
                Id = s.Id,
                Name = s.Name,
                Description = s.Description,

            }).ToList();

            return View(courseDetail);
        }

        [Authorize]
        public IActionResult TeacherDetail(string Id)
        {
            IList<CourseViewModel> courseDetail = (from course in _dbContext.Courses
                                                   join tc in _dbContext.TeacherCourses
                                                   on course.Id equals tc.CourseId
                                                   join teacher in _dbContext.Teachers
                                                   on tc.TeacherId equals teacher.Id

                                                   where teacher.Email==Id
             select new CourseViewModel
            {
                Id = course.Id,
                Name = course.Name,
                Description = course.Description,

            }).ToList();

            return View(courseDetail);
        }

        [Authorize]
        public IActionResult StudentDetail(string Id)
        {
            IList<CourseViewModel> courseDetail = (from course in _dbContext.Courses
                                                   join batch in _dbContext.Batches
                                                   on course.Id equals batch.CourseId
                                                   join sb in _dbContext.StudentBatches
                                                   on batch.Id equals sb.BatchId
                                                   join student in _dbContext.Students
                                                   on sb.StudentId equals student.Id

                                                   where student.Email == Id
                                                   select new CourseViewModel
                                                   {
                                                       Id = course.Id,
                                                       Name = course.Name,
                                                       Description = course.Description,

                                                   }).ToList();

            return View(courseDetail);
        }


        [Authorize]
        public IActionResult Delete(string Id)
        {
            try
            {
                var deleteCourseData = _dbContext.Courses.Where(w => w.Id == Id).FirstOrDefault();
                if(deleteCourseData is not null)
                {
                    _dbContext.Courses.Remove(deleteCourseData);
                    _dbContext.SaveChanges();
                }
                TempData["info"] = "delete successfully the record";
            }
            catch (Exception e)
            {
                TempData["info"] = "error while deleting the record";
            }
            return RedirectToAction("List");
        }

        [Authorize]
        public IActionResult Edit(string Id)
        {
            
                CourseViewModel editCourseData = _dbContext.Courses.Where(w => w.Id == Id).Select(s => new CourseViewModel
                {
                    Id = s.Id,
                    Name = s.Name,
                    Description = s.Description,
                    
                }).FirstOrDefault();

               
            return View(editCourseData);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Update(CourseViewModel ui)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    CourseEntity updateCourseData = new CourseEntity()
                    {
                        Id = ui.Id,
                        CreatedAt = DateTime.UtcNow,
                        ModifiedAt = DateTime.UtcNow,
                        IsInActive = true,
                        Name = ui.Name,
                        Description = ui.Description,
                        
                    };

                    _dbContext.Courses.Update(updateCourseData);
                    _dbContext.SaveChanges();
                    TempData["info"] = "update successfully the record";
                }
                else
                {
                    return View("Edit", model: ui);
                }
            }
            catch (Exception e)
            {
                TempData["info"] = "error while updating the record";
            }
            return RedirectToAction("List");
        }

        [Authorize]
        public IActionResult Cancle(CourseViewModel ui)
        {
            CourseEntity course = new CourseEntity()
            {
                Name = "",
                Description = "",
            };
            return RedirectToAction("entry");
        }
    }
}

StudentManagementSystem/Views/Course/Detail.cshtml
@model IList<CourseViewModel>
<div class="container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/home/index">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Course</li>
        </ol>
    </nav>
    @if (User.IsInRole("Admin"))
    {
        <h1 class="h4 mt-3">Courses:</h1>
        <div class="row">
            @foreach (var detail in Model)
            {
                <div class="col-lg-6 my-3">
                    <div class="card shadow">
                        <div class="card-body">
                            <h1 class="h5"><span class="fw-bold">Course: </span> @detail.Name</h1>
                            <p class="card-text"><span class="fw-bold">Description: </span> @detail.Description</p>
                            
                        </div>
                        @if (User.IsInRole("Admin"))
                        {
                            <div class="card-footer">
                                <a asp-controller="Batch" asp-action="AdminDetail" asp-route-id="@detail.Id" class="btn btn-primary float-end">Details >></a>
                            </div>
                        }
                    </div>
                </div>
            }

        </div>
    }
</div>

StudentManagementSystem/Views/Course/Edit.cshtml
@model StudentManagementSystem.Models.ViewModels.CourseViewModel
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/home/index">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Edit</li>
    </ol>
</nav>
<div class="container w-50 mx-auto mt-5 p-5 border-start border-end border-bottom rounded-start rounded-end shadow-sm" style="border-top: 12px solid #699BF7">
    <div class="d-flex justify-content-center align-items-center mb-4">
        <div class="me-3">
            <i class="fa-solid fa-book-open fa-2xl" style="color: #699BF7"></i>
        </div>
        <div class="text-center">
            <span class="mate-sc text-uppercase fw-bold">Leadership</span>
            <h1 class="h5 brand-space">Excellence</h1>
        </div>
    </div>
    <h1 class="h4 mb-3 text-center">To Edit Course</h1>
    <form asp-controller="Course" asp-action="Update" method="post" enctype="multipart/form-data">
        <input asp-for="Id" hidden />
        <div class="mb-3">
            <label asp-for="Name" class="form-label">Name</label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="Description" class="form-label">Description</label>
            <input asp-for="Description" class="form-control"  />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
       
        <div class="mb-3">
            <button class="btn btn-primary text-white" style="border-radius: 10px 0 10px 0;">Update</button>
            <a href="/course/cancle" class="btn btn-danger" style="border-radius: 10px 0 10px 0;">
                Cancel
            </a>
        </div>
    </form>
</div>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

StudentManagementSystem/Views/Course/Entry.cshtml
@model StudentManagementSystem.Models.ViewModels.CourseViewModel
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/home/index">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Entry</li>
    </ol>
</nav>
<div class="container w-50 mx-auto mt-5 p-5 border-start border-end border-bottom rounded-start rounded-end shadow-sm" style="border-top: 12px solid #699BF7">
    <div class="d-flex justify-content-center align-items-center mb-4">
        <div class="me-3">
            <i class="fa-solid fa-book-open fa-2xl" style="color: #699BF7"></i>
        </div>
        <div class="text-center">
            <span class="mate-sc text-uppercase fw-bold">Leadership</span>
            <h1 class="h5 brand-space">Excellence</h1>
        </div>
    </div>
    <h1 class="h4 mb-3 text-center">Course Entry Form</h1>
    <form asp-controller="Course" asp-action="Entry" method="post" enctype="multipart/form-data">
        <input asp-for="Id" value="@ViewBag.Id" hidden />
        <div class="mb-3">
            <label asp-for="Name" class="form-label">Name</label>
            <input asp-for="Name" class="form-control" placeholder="Enter Name..." />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="Description" class="form-label">Description</label>
            <input asp-for="Description" class="form-control" placeholder="Enter Description..." />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <button class="btn btn-primary text-white" style="border-radius: 10px 0 10px 0;">Submit</button>
            <a href="/course/cancle" class="btn btn-danger" style="border-radius: 10px 0 10px 0;">
                Cancel
            </a>
        </div>
    </form>
</div>


@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

StudentManagementSystem/Views/Course/List.cshtml
@model IList<CourseViewModel>
@if (TempData["info"] != null)
{
    @if (TempData["info"].ToString().Contains("delete"))
    {
        <div class="alert alert-danger mt-3" role="alert">
            @TempData["info"]
        </div>
    }
    else
    {
        <div class="alert alert-success mt-3" role="alert">
            @TempData["info"]
        </div>
    }
}

    
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/home/index">Home</a></li>
                <li class="breadcrumb-item active" aria-current="page">List</li>
            </ol>
        </nav>
        @if (User.IsInRole("Admin"))
        {
            
            <div class="row">

                <h1 class="h4 mb-3">Course List</h1>
                <div class="col-md-12">
                    <div class="table-responsive">
                        <table id="courseTable" class="table table-bordred table-striped">

                            <thead>
                            <th>Course Name</th>
                            <th>Description</th>
                                @if (User.IsInRole("Admin"))
                                {
                                    <th>Action</th>
                                    <th>Details</th>
                                }
                            </thead>
                            <tbody>
                                @{
                                    var index = 1;
                                }
                                @foreach(var list in Model)
                                {
                            
                                    <tr>
                                        <td>@list.Name</td>
                                        <td>@list.Description</td>
                                        
                                        @if (User.IsInRole("Admin"))
                                        {
                                            <td>
                                                <div class="dropdown">
                                                    <button class="btn btn-white dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">Action</button>
                                                        <ul class="dropdown-menu">

                                                            <li>
                                                                <a type="button" class="dropdown-item btn text-info btn-xs mb-2" href="/course/edit?Id=@list.Id">
                                                                    <i class="fa-regular fa-pen-to-square"></i> Edit
                                                                </a>
                                                            </li>
                                                            <li class="">
                                                                <a type="button" class="dropdown-item btn text-danger btn-xs " asp-controller="Course" asp-action="Delete" asp-route-Id="@list.Id" onclick="return confirm('Are you sure want to delete the record?')">
                                                                    <i class="fa-regular fa-trash-can"></i> Delete
                                                                </a>
                                                            </li>
                                                        </ul>
                                                </div>
                                            </td>
                                            <td>
                                                <a asp-controller="Batch" asp-action="AdminDetail" asp-route-id="@list.Id" class="link-underline-primary link-underline-opacity-100-hover">Details>></a>
                                            </td>
                                        }
                                    </tr>
                                    index++;

                                }
                            </tbody>

                        </table>

                    </div>

                </div>
            </div>
        }
    </div>



<script>
    $(document).ready(function () {
        $("#courseTable").DataTable();
    });
</script>

StudentManagementSystem/Views/Course/StudentDetail.cshtml
@model IList<CourseViewModel>
<div class="container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/home/index">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Course</li>
        </ol>
    </nav>
    @if (User.Identity.IsAuthenticated)
    {
        <h1 class="h4 mt-3">Courses:</h1>
        <div class="row">
            @foreach (var detail in Model)
            {
                <div class="col-lg-6 my-3">
                    <div class="card shadow">
                        <div class="card-body">
                            <h1 class="h5"><span class="fw-bold">Course: </span> @detail.Name</h1>
                            <p class="card-text"><span class="fw-bold">Description: </span> @detail.Description</p>

                        </div>

                        <div class="card-footer">
                            <a asp-controller="Batch" asp-action="StudentDetail" asp-route-id="@detail.Id" class="btn btn-primary float-end">Details >></a>
                        </div>

                    </div>
                </div>
            }

        </div>
    }
</div>

StudentManagementSystem/Views/Course/TeacherDetail.cshtml
@model IList<CourseViewModel>
<div class="container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/home/index">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Course</li>
        </ol>
    </nav>
    @if (User.Identity.IsAuthenticated)
    {
        <h1 class="h4 mt-3">Courses:</h1>
        <div class="row">
            @foreach (var detail in Model)
            {
                <div class="col-lg-6 my-3">
                    <div class="card shadow">
                        <div class="card-body">
                            <h1 class="h5"><span class="fw-bold">Course: </span> @detail.Name</h1>
                            <p class="card-text"><span class="fw-bold">Description: </span> @detail.Description</p>

                        </div>
                        
                            <div class="card-footer">
                                <a asp-controller="Batch" asp-action="TeacherDetail" asp-route-id="@detail.Id" class="btn btn-primary float-end">Details >></a>
                            </div>
                        
                    </div>
                </div>
            }

        </div>
    }
</div>