StudentManagementSystem/Models/ViewModels/ExamResultViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudentManagementSystem.Models.ViewModels
{
    public class ExamResultViewModel
    {
        public string Id { get; set; }
        [Required(ErrorMessage ="Mark is required")]
        public int Mark { get; set; }
        [Required(ErrorMessage = "Student Name is required")]
        public string StudentId { get; set; }
    }
}

StudentManagementSystem/Controllers/ExamResultController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StudentManagementSystem.DAO;
using StudentManagementSystem.Models.DataModels;
using StudentManagementSystem.Models.ViewModels;

namespace StudentManagementSystem.Controllers
{
    public class ExamResultController : Controller
    {
        private readonly SMSDbContext _dbContext;
        public ExamResultController(SMSDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [Authorize]
        public IActionResult Entry()
        {
            ViewBag.Id = Guid.NewGuid().ToString();

            var students = (from student in _dbContext.Students
                            join sb in _dbContext.StudentBatches
                            on student.Id equals sb.StudentId
                            join batch in _dbContext.Batches
                            on sb.BatchId equals batch.Id
                            join course in _dbContext.Courses
                            on batch.CourseId equals course.Id

                            select new StudentViewModel
                            {
                                Id = student.Id,
                                Name = student.Name+"/ "+batch.Name+"/ "+course.Name
                            }).OrderBy(o => o.Name).ToList();
            ViewBag.Student = students;

            return View();
        }

        [HttpPost]
        [Authorize]
        public IActionResult Entry(ExamResultViewModel ui)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    ExamResultEntity examResultData = new ExamResultEntity()
                    {
                        Id = ui.Id,
                        CreatedAt = DateTime.UtcNow,
                        IsInActive = true,
                        Mark = ui.Mark,
                        StudentId = ui.StudentId,
                    };
                    _dbContext.ExamResults.Add(examResultData);
                    _dbContext.SaveChanges();
                    TempData["info"] = "Added successfully the exam result";
                }
                else
                {
                    //Reload Id, StudentId to populate the dropdown again

                    ViewBag.Id = Guid.NewGuid().ToString();

                    var students = (from student in _dbContext.Students
                                    join sb in _dbContext.StudentBatches
                                    on student.Id equals sb.StudentId
                                    join batch in _dbContext.Batches
                                    on sb.BatchId equals batch.Id
                                    join course in _dbContext.Courses
                                    on batch.CourseId equals course.Id

                                    select new StudentViewModel
                                    {
                                        Id = student.Id,
                                        Name = student.Name + "/ " + batch.Name + "/ " + course.Name
                                    }).OrderBy(o => o.Name).ToList();
                    ViewBag.Student = students;

                    return View(ui);
                }
            }
            catch (Exception e)
            {
                TempData["info"] = "error while saving the record";
            }

            if (User.IsInRole("Admin"))
            {
                return RedirectToAction("List");
            }
            else
            {
                return Redirect("/Home/Index");
            }
        }

        [Authorize]
        public IActionResult List()
        {
            IList<ExamResultViewModel> examResultList = (from examResult in _dbContext.ExamResults
                                                      join sb in _dbContext.StudentBatches
                                                      on examResult.StudentId equals sb.StudentId
                                                      join student in _dbContext.Students
                                                      on examResult.StudentId equals student.Id
                                                      join batch in _dbContext.Batches
                                                      on sb.BatchId equals batch.Id
                                                      join course in _dbContext.Courses
                                                      on batch.CourseId equals course.Id
                                                         
                                                      where examResult.StudentId == sb.StudentId

                                                      select new ExamResultViewModel
                                                      {
                                                          Id = examResult.Id,
                                                          Mark = examResult.Mark,
                                                          StudentId = student.Name+"/ "+batch.Name+"/ "+course.Name,
                                                      }).ToList();
            return View(examResultList);
        }

        [Authorize]
        public IActionResult Detail()
        {
            IList<ExamResultViewModel> examResultDetail = (from examResult in _dbContext.ExamResults
                                                         join sb in _dbContext.StudentBatches
                                                         on examResult.StudentId equals sb.StudentId
                                                         join student in _dbContext.Students
                                                         on examResult.StudentId equals student.Id
                                                         join batch in _dbContext.Batches
                                                         on sb.BatchId equals batch.Id
                                                         join course in _dbContext.Courses
                                                         on batch.CourseId equals course.Id

                                                         where examResult.StudentId == sb.StudentId

                                                         select new ExamResultViewModel
                                                         {
                                                             Id = examResult.Id,
                                                             Mark = examResult.Mark,
                                                             StudentId = student.Name + "/ " + batch.Name + "/ " + course.Name,
                                                         }).ToList();
            return View(examResultDetail);
        }

        [Authorize]
        public IActionResult TeacherDetail(string Id)
        {
            IList<ExamResultViewModel> examResultDetail = (from examResult in _dbContext.ExamResults
                                                           join sb in _dbContext.StudentBatches
                                                           on examResult.StudentId equals sb.StudentId
                                                           join student in _dbContext.Students
                                                           on examResult.StudentId equals student.Id
                                                           join batch in _dbContext.Batches
                                                           on sb.BatchId equals batch.Id
                                                           join course in _dbContext.Courses
                                                           on batch.CourseId equals course.Id
                                                           join tc in _dbContext.TeacherCourses
                                                           on course.Id equals tc.CourseId
                                                           join teacher in _dbContext.Teachers
                                                           on tc.TeacherId equals teacher.Id

                                                           where teacher.Email == Id

                                                           select new ExamResultViewModel
                                                           {
                                                               Id = examResult.Id,
                                                               Mark = examResult.Mark,
                                                               StudentId = student.Name + "/ " + batch.Name + "/ " + course.Name,
                                                           }).ToList();
            return View(examResultDetail);
        }

        [Authorize]
        public IActionResult StudentDetail(string Id)
        {
            IList<ExamResultViewModel> examResultDetail = (from examResult in _dbContext.ExamResults
                                                           join sb in _dbContext.StudentBatches
                                                           on examResult.StudentId equals sb.StudentId
                                                           join student in _dbContext.Students
                                                           on examResult.StudentId equals student.Id
                                                           join batch in _dbContext.Batches
                                                           on sb.BatchId equals batch.Id
                                                           join course in _dbContext.Courses
                                                           on batch.CourseId equals course.Id
                                                           

                                                           where student.Email == Id

                                                           select new ExamResultViewModel

StudentManagementSystem/Views/ExamResult/Detail.cshtml
@model IList<ExamResultViewModel>
<div class="container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/home/index">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">ExamResult</li>
        </ol>
    </nav>
    @if (User.IsInRole("Admin"))
    {
        <h1 class="h4 mt-3">Exam Results:</h1>
        <div class="row">
            @foreach (var detail in Model)
            {
                <div class="col-lg-5 mb-5">
                    <div class="card shadow">
                        <div class="card-body">
                            <h1 class="h5"><span class="fw-bold">Student: </span> @detail.StudentId</h1>
                            <p class="card-text"><span class="fw-bold">Mark: </span> @detail.Mark</p>

                        </div>
                        
                    </div>
                </div>
            }

        </div>
    }
</div>

StudentManagementSystem/Views/ExamResult/Edit.cshtml
@model StudentManagementSystem.Models.ViewModels.ExamResultViewModel
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/home/index">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Edit</li>
    </ol>
</nav>
<div class="container w-50 mx-auto mt-5 p-5 border-start border-end border-bottom rounded-start rounded-end shadow-sm" style="border-top: 12px solid #699BF7">
    <div class="d-flex justify-content-center align-items-center mb-4">
        <div class="me-3">
            <i class="fa-solid fa-book-open fa-2xl" style="color: #699BF7"></i>
        </div>
        <div class="text-center">
            <span class="mate-sc text-uppercase fw-bold">Leadership</span>
            <h1 class="h5 brand-space">Excellence</h1>
        </div>
    </div>
    <h1 class="h4 mb-3 text-center">To Edit Exam Result</h1>
    <form asp-controller="ExamResult" asp-action="Update" method="post" enctype="multipart/form-data">
        <input asp-for="Id" hidden />
        <div class="mb-3">
            <label asp-for="Mark" class="form-label">Mark</label>
            <input type="number" asp-for="Mark" class="form-control" />
            <span asp-validation-for="Mark" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="StudentId" class="form-label">Student</label>
            <select asp-for="StudentId" class="form-select">
                <option value="">---choose option---</option>
                @foreach (var student in ViewBag.Student)
                {
                    if(@student.Id == Model.StudentId)
                    {
                        <option value="@student.Id" selected>@student.Name</option>
                    }
                }
            </select>
            <span asp-validation-for="StudentId" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <button class="btn btn-primary text-white" style="border-radius: 10px 0 10px 0;">Submit</button>
            <a href="/examresult/cancle" class="btn btn-danger" style="border-radius: 10px 0 10px 0;">
                Cancel
            </a>
        </div>
    </form>
</div>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

StudentManagementSystem/Views/ExamResult/Entry.cshtml
@model StudentManagementSystem.Models.ViewModels.ExamResultViewModel
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/home/index">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Entry</li>
    </ol>
</nav>
<div class="container w-50 mx-auto mt-5 p-5 border-start border-end border-bottom rounded-start rounded-end shadow-sm" style="border-top: 12px solid #699BF7">
    <div class="d-flex justify-content-center align-items-center mb-4">
        <div class="me-3">
            <i class="fa-solid fa-book-open fa-2xl" style="color: #699BF7"></i>
        </div>
        <div class="text-center">
            <span class="mate-sc text-uppercase fw-bold">Leadership</span>
            <h1 class="h5 brand-space">Excellence</h1>
        </div>
    </div>
    <h1 class="h4 mb-3 text-center">Exam Result Form</h1>
    <form asp-controller="ExamResult" asp-action="Entry" method="post" enctype="multipart/form-data">
        <input asp-for="Id" value="@ViewBag.Id" hidden />
        <div class="mb-3">
            <label asp-for="StudentId" class="form-label">Student</label>
            <select asp-for="StudentId" class="form-select">
                <option value="" selected>---choose option---</option>
                @foreach (var student in ViewBag.Student)
                {
                    <option value="@student.Id">@student.Name</option>
                }
            </select>
            <span asp-validation-for="StudentId" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Mark" class="form-label">Mark</label>
            <input type="number" asp-for="Mark" class="form-control" placeholder="Enter mark..." />
            <span asp-validation-for="Mark" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <button class="btn btn-primary text-white" style="border-radius: 10px 0 10px 0;">Submit</button>
            <a href="/examresult/cancle" class="btn btn-danger" style="border-radius: 10px 0 10px 0;">
                Cancel
            </a>
        </div>
    </form>
</div>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

StudentManagementSystem/Views/ExamResult/List.cshtml
@model IList<ExamResultViewModel>
@if (TempData["info"] != null)
{
    @if (TempData["info"].ToString().Contains("delete"))
    {
        <div class="alert alert-danger mt-3" role="alert">
            @TempData["info"]
        </div>
    }
    else
    {
        <div class="alert alert-success mt-3" role="alert">
            @TempData["info"]
        </div>
    }
}
<div class="container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/home/index">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">List</li>
        </ol>
    </nav>
    @if (User.IsInRole("Admin"))
    {
        
        <div class="row">

            <h1 class="h4 mb-3">Exam Result List</h1>
            <div class="col-md-12">
                <div class="table-responsive">
                    <table id="examResultTable" class="table table-bordred table-striped">

                        <thead>
                            <th>Mark</th>
                            <th>Student</th>
                                @if (User.IsInRole("Admin")||User.IsInRole("Teacher"))
                                {
                                    <th>Action</th>
                                }
                        </thead>
                        <tbody>
                            @{
                                var index = 1;
                            }
                            @foreach(var list in Model)
                            {
                            
                                <tr>
                                    <td>@list.Mark marks</td>
                                    <td>@list.StudentId</td>
                                    @if (User.IsInRole("Admin") || User.IsInRole("Teacher"))
                                    {
                                        <td>
                                            <div class="dropdown">
                                                <button class="btn btn-white dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">Action</button>
                                                    <ul class="dropdown-menu">

                                                        <li>
                                                            <a type="button" class="dropdown-item btn text-info btn-xs mb-2" href="/examresult/edit?Id=@list.Id">
                                                                <i class="fa-regular fa-pen-to-square"></i> Edit
                                                            </a>
                                                        </li>
                                                    @if (User.IsInRole("Admin"))
                                                    {
                                                        <li class="">
                                                            <a type="button" class="dropdown-item btn text-danger btn-xs " asp-controller="ExamResult" asp-action="Delete" asp-route-Id="@list.Id" onclick="return confirm('Are you sure want to delete the record?')">
                                                                <i class="fa-regular fa-trash-can"></i> Delete
                                                            </a>
                                                        </li>
                                                    }
                                                    </ul>
                                            </div>
                                        </td>
                                    }
                                </tr>
                                index++;
                            }

                        </tbody>

                    </table>

                </div>

            </div>
        </div>
    }
</div>


<script>
    $(document).ready(function () {
        $("#examResultTable").DataTable();
    });
</script>

StudentManagementSystem/Views/ExamResult/StudentDetail.cshtml
@model IList<ExamResultViewModel>
<div class="container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/home/index">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">ExamResult</li>
        </ol>
    </nav>
    @if (User.Identity.IsAuthenticated)
    {
        <h1 class="h4 mt-3">Exam Results:</h1>
        <div class="row">
            @foreach (var detail in Model)
            {
                <div class="col-lg-5 mb-5">
                    <div class="card shadow">
                        <div class="card-body">
                            <h1 class="h5"><span class="fw-bold">Student: </span> @detail.StudentId</h1>
                            <p class="card-text"><span class="fw-bold">Mark: </span> @detail.Mark</p>

                        </div>

                    </div>
                </div>
            }

        </div>
    }
</div>

StudentManagementSystem/Views/ExamResult/TeacherDetail.cshtml
@model IList<ExamResultViewModel>
<div class="container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/home/index">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">ExamResult</li>
        </ol>
    </nav>
    @if (User.Identity.IsAuthenticated)
    {
        <h1 class="h4 mt-3">Exam Results:</h1>
        <div class="row">
            @foreach (var detail in Model)
            {
                <div class="col-lg-5 mb-5">
                    <div class="card shadow">
                        <div class="card-body">
                            <h1 class="h5"><span class="fw-bold">Student: </span> @detail.StudentId</h1>
                            <p class="card-text"><span class="fw-bold">Mark: </span> @detail.Mark</p>

                        </div>

                    </div>
                </div>
            }

        </div>
    }
</div>